import type { ModuleSpec, LayoutNode } from '../domain/module-spec';
import { toHubSpotFieldsJson } from './hubspot-fields';

export interface GeneratedFiles {
  [path: string]: string;
}

const renderNode = (spec: ModuleSpec, node: LayoutNode): string => {
  const renderChildren = () =>
    'children' in node
      ? (node.children ?? []).map((c) => renderNode(spec, c)).join('\n')
      : '';

  switch (node.kind) {
    case 'section':
      return `
<section class="hsmb-section">
  ${renderChildren()}
</section>`.trim();

    case 'stack':
      return `
<div class="hsmb-stack">
  ${renderChildren()}
</div>`.trim();

    case 'slot': {
      const field = spec.fields.find((f) => f.id === node.bindFieldId);
      if (!field) {
        return `<!-- slot ${node.id}: missing binding -->`;
      }
      return `
<div class="hsmb-slot">
  {% if module.${field.name} %}
    {{ module.${field.name} }}
  {% endif %}
</div>`.trim();
    }

    default:
      return `<!-- Unknown node kind -->`;
  }
};

export const generateModuleFiles = (spec: ModuleSpec): GeneratedFiles => {
  const slug = spec.module.slug.trim() || 'module';
  const basePath = `${slug}.module`;

  const hubspotFields = JSON.stringify(
    toHubSpotFieldsJson(spec.fields),
    null,
    2
  );

  const moduleHtml = `
{# Generated by hs-module-builder #}
<div class="hsmb-root">
${renderNode(spec, spec.layout)}
</div>
`.trim();

  const moduleCss = `
/* Generated by hs-module-builder */
.hsmb-root { width: 100%; }
.hsmb-section { padding: 24px; border: 1px solid rgba(255,255,255,.12); }
.hsmb-stack { display: grid; gap: 12px; }
.hsmb-slot { min-height: 16px; }
`.trim();

  const moduleJs = `
/* Generated by hs-module-builder */
/* Intentionally empty for MVP */
`.trim();

  const contentTypes = spec.module.contentTypes?.length
    ? spec.module.contentTypes
    : ['SITE_PAGE', 'LANDING_PAGE'];

  const metaJson = JSON.stringify(
    {
      label: spec.module.name,
      content_types: contentTypes,
      is_available_for_new_content: true,
    },
    null,
    2
  );

  return {
    [`${basePath}/module.html`]: moduleHtml,
    [`${basePath}/module.css`]: moduleCss,
    [`${basePath}/module.js`]: moduleJs,
    [`${basePath}/fields.json`]: hubspotFields,
    [`${basePath}/meta.json`]: metaJson,
  };
};
